service: coopartilhar-serverless
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  lambdaHashingVersion: 20201221
  # stage: prd

  logRetentionInDays: 30

  environment:
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}

# Files on package
package:
  individually: true
  patterns:
    - "dist/**"
    - "files/"
    - "!.data/**"
    - "!src/**"
    - "!package.json"
    - "!package-lock.json"
    - "!pnpm-lock.yaml"
    - "!env-example"
    - "!test/**"
    - "!docs/**"
    - "!.husky/**"
    - "!.hygen*"
    - "!*docker*"
    - "!*Dockerfile*"
    - "!*.md"
    - "!*.sh"
    - "!*.js"
    - "!*.json"

custom:
  serverless-offline:
    httpPort: 4000
  prune:
    automatic: true
    number: 3

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

  api_url:
    handler: dist/handler.handler
    timeout: 30
    memorySize: 512
    url:
      cors:
        allowedOrigins:
          - '*'
        allowedHeaders:
          - '*'
        allowedMethods:
          - '*'

    layers:
      - arn:aws:lambda:sa-east-1:580247275435:layer:LambdaInsightsExtension:51